### ISSUE TITLE
Request for Copy-Paste or Duplicate Functionality

### ISSUE THREAD

**Issue by kzkiyo** [1943time/bluestone#10]
Thank you for developing this fantastic markdown editor. I really appreciate your work.

I would like to request a feature for copying or duplicating files. There could be various methods to achieve this, such as allowing users to copy-paste files or adding a 'Duplicate' button upon right-clicking a file.

Currently, copying the source code of a markdown file is possible, but it introduces unwanted blank spaces. Moreover, the process involves multiple steps. Having a dedicated copy-paste or duplicate functionality would greatly enhance the user experience.

I'm curious to know if there are any plans to implement such a feature in future updates. Thank you!

**Comment by 1943time** [comment]
Electron currently only supports copying files from the Mac system. It will add the functions of copying files and copying folders in the right-click menu of the next version of the file tree. You are currently using a Mac computer and should be able to temporarily solve your problem. Thank you for your feedback.

**Comment by 1943time** [comment]
<img width="260" alt="image" src="https://github.com/1943time/bluestone/assets/115093678/0ed0541d-5617-4f76-bb69-b52a64d5dc4f">

**Comment by kzkiyo** [comment]
Thanks for the info! Excited to hear about the upcoming file copy feature in the next version. Appreciate the quick response and ongoing improvements!

**Comment by kzkiyo** [comment]
Hi there,

I've recently updated to the new version 1.4.10 and noticed the ability to select "Copy File."

Is this feature intended to function like copying the path of the source? Currently, when pasting into a markdown file, it creates a link.

It would be great if we could copy files individually, allowing us to create new files by duplicating them. Looking forward to a possible update in the future!

**Comment by 1943time** [comment]
The current copy is pasted into the system folder. Is your requirement to create a new copy on a document？

**Comment by kzkiyo** [comment]
Currently, when I click "Copy File" and then use Command+V to paste, nothing seems to happen. Ideally, I would expect the file to be duplicated. My initial expectation was that copying and pasting "a_markdown.md" would result in something like "a_markdown_copied.md."

And now, I can only paste it in a markdown editor and it creates a link with the file name.

Is there a specific process or setting I might be missing, or is this a feature that could be different what you think?

**Comment by 1943time** [comment]
I understand. Currently, the folder in the file tree cannot be selected, so adding a file copy can only be done in the current directory. After creating a new copy, you can drag it to another directory. I can add the option to add copy to the right-click menu.

**Comment by kzkiyo** [comment]
I see. At present, it's not possible to create a new copy, and pressing 'Copy File' doesn't result in any action. Moreover, the file isn't being copied to the current directory.

The expected behavior is that the 'Copy File' operation should create a new copy in the current directory. However, at the moment, this functionality doesn't seem to be working as intended.

I really appreciate your earlier response.

**Comment by 1943time** [comment]
ok, this function will be added in the next version.
