### ISSUE TITLE
<ruby><rt></rt></ruby> support

### ISSUE THREAD

**Issue by yu2chuan** [1943time/bluestone#15]
is it possibel to support this format? \<ruby>\<rt>\</rt>\</ruby>
I have many notes in Japanese with this format.
I will really really appreiate your effort if the Bluestone can support this format.

**Comment by 1943time** [comment]
Currently, Bluestone does not support inline HTML rendering, but you can create an HTML rendering area to render it as follows:
<img width="832" alt="image" src="https://github.com/1943time/bluestone/assets/115093678/07bd9240-83ff-4d8f-a860-0fc89857eb46">
Type any Html tag at the beginning of the paragraph and press Enter, I don’t know if it can solve some of the problems?

**Comment by yu2chuan** [comment]
I will try. Thanks for this information.

**Comment by 1943time** [comment]
Close this issue first, If you have any other questions, you can open again.
