### ISSUE TITLE
recent 3 used file on the top tab.

### ISSUE THREAD

**Issue by yu2chuan** [1943time/bluestone#16]
currently, I can't find a easy way to switch two or three open md files.
Is it possible the recent 3 open files can be shown on the top tab?
And users are allowed to change 3 to 4 or 5 in the settings.

**Comment by 1943time** [comment]
The editor supports multi tab editing mode, and I don't understand how you want to open three markdown files simultaneously, Can you describe it more.

**Comment by yu2chuan** [comment]
I often consolidate several notes into one.

**Comment by wrdhl** [comment]
Press the Ctrl key, then click to open the second or third document you need？

**Comment by yu2chuan** [comment]
Yes, it works as I expected after upgarding.
However, when "Ctrl+open" repeatedly open the same file, could the bluestone give a message instead of really opening the same file, which may consume extra memories?

**Comment by 1943time** [comment]
The logic for the next version will change to when opening the next tab, if the file has already been opened by another tab, select the other tab instead of creating it.
