### ISSUE TITLE
切换焦点后不能恢复到原输入位置，而是跳到文档第一行

### ISSUE THREAD

**Issue by xlzhu** [1943time/bluestone#19]
环境：macos 14.2.1
版本：App Store 安装版
描述：不管是全屏状态还是非全屏状态，当将焦点切换到其他 App 再返回时，很大几率会导致输入焦点会跳到文档第一行

**Comment by 1943time** [comment]
升级下版本再试试，目前mac store是1.5.2版本

**Comment by 1943time** [comment]
我看错 你的是系统版本 我这边没有复现，是否方便截图或录屏呢

**Comment by xlzhu** [comment]
> 我看错 你的是系统版本 我这边没有复现，是否方便截图或录屏呢

好的，我晚点录屏提交上来

**Comment by 1943time** [comment]
请问是否有程序在焦点切换时，立即修改了这个markdown文件，或者自动格式化之类的工具进行了操作？

**Comment by xlzhu** [comment]
> 请问是否有程序在焦点切换时，立即修改了这个markdown文件，或者自动格式化之类的工具进行了操作，关闭正在打开或使用这个markdown的其他程序试一下呢？

这个文件是保存在 OneDrive 同步目录里面的，是不是因为这个原因呢？目前我复制到桌面上再打开，还没有重现这个问题

**Comment by 1943time** [comment]
不能确认是因为这个，但是青石编辑器会在失去焦点时，监听这个文件的变化，如果文件出现变化，会自动刷新这个文档，光标就会回到起始位。我会在下个版本文件变化后尝试回到原来的位置，如果找不到再回到起始位。

**Comment by xlzhu** [comment]
[《持续交付 2.0》 书摘_副本.md](https://github.com/1943time/bluestone/files/13843897/2.0._.md)
做测试的这份文件使用 Bluestone 打开是空白的，但是其他的编辑器是可以打开的，例如：VSCode 或 Typora

**Comment by 1943time** [comment]
<img width="434" alt="image" src="https://github.com/1943time/bluestone/assets/115093678/9371edc7-27e3-45a2-bdbd-f1af7ff5b215">
空白的块引用导致了解析错误，感谢反馈，已经修复，在下个版本发布

**Comment by 1943time** [comment]
如果没有其它问题我先关闭这个issues了，下个版本会修正这些问题。
