### ISSUE TITLE
Small UX improvements

### ISSUE THREAD

**Issue by ww-wolt** [1943time/bluestone#21]
I really like the app, great work!!

There are only two things that sometimes interrupt my workflow:

**1. No drag and drop dupport when dragging in files from the finder into an folder inside Bluestone**

I often find myself dragging in images, pdfs, videos or other files next to the markdown files. Unfortunately directly dragging from Finder or Downloads Stack into the bluestone folder view is not supported. It would be great to add that functionality!
(For images I know that I can directly drop them into the markdown files, but as I am working with a lot of subdirectories I prefer them to be in the specific subdirectory of the note and not all in one global folder. Maybe it would also be cool to add the option to set an relative path as image storage folder in settings like for example "./images", that is then always relative to the note file)

**2. No keyboard shortcut for deleting files in the folder view.** 
It would be great to add the keyboard shortcut `Cmd + Backspace` on Mac (maybe `Delete` on Windows) for deleting files or folders. Ideally with a little keyboard navigable warning popup similar to the one in VSCode.

Mac OS Ventura 13.6, Bluestone Version 0.12.7

**Comment by 1943time** [comment]
Hello, the feature you mentioned is indeed quite practical. I am currently working on enhancing the stability of the editor. Regarding the feature you mentioned, I will release it in a future version, which may take 2-3 versions to complete. Please wait for a while.

**Comment by 1943time** [comment]
The latest version has added these features and you can try using them.

**Comment by ww-wolt** [comment]
Thank you so much for this extremely quick implementation!! So awesome!! :))
