### ISSUE TITLE
Bullet points in front of TODO items

### ISSUE THREAD

**Issue by chen-yingfa** [1943time/bluestone#25]
Currently, a TODO item has a bullet point to the left, as shown below.

<img width="102" alt="image" src="https://github.com/1943time/bluestone/assets/54496664/349b9c63-7844-4a99-a4de-fea35070bcf8">

I think this should be hidden, which is the norm in most Markdown renderers such as GitHub, as shown below.

- [ ] test.

**Comment by 1943time** [comment]
<img width="833" alt="image" src="https://github.com/1943time/bluestone/assets/115093678/58425082-e74e-4bec-ae4a-251ff9a293ca">
Most editors do indeed implement it this way, with the prefix I want to distinguish between ordered and unordered task lists

**Comment by chen-yingfa** [comment]
Ah, I see your reasoning, but is it possible to have the option to turn it off so that the rendered document appears the same as in other editors?

**Comment by 1943time** [comment]
I can consider adding it to a later version, but cannot confirm the specific time.
