### ISSUE TITLE
支持调整行高大小

### ISSUE THREAD

**Issue by imoyy** [1943time/bluestone#27]
> 行高 Line Height 的调整
> 就是这个
> ![image](https://github.com/1943time/bluestone/assets/115197762/99064e68-aacc-4191-b531-5560cb01c20a)

非常感谢您的付出，软件使用起来体验很好，作为一个本地的markdown编辑器很不错。请问有计划支持更多的编辑器外观自定义选项吗吗？对我来说，文字比较密集的情境下的行高有点少，所以如果可以支持自定义调整行高就更好了！
感谢！

**Comment by 1943time** [comment]
你好，可以支持段落行高调整，标题行高目前不方便调整

**Comment by 1943time** [comment]
新版段落行高可进行3个选项的调整。

**Comment by imoyy** [comment]
> 新版段落行高可进行3个选项的调整。

非常感谢您
