### ISSUE TITLE
当文件保存在 OneDrive 同步目录中，保留列表，但不输人内容，切换焦点时，会导致输入焦点跳转到第一行

### ISSUE THREAD

**Issue by xlzhu** [1943time/bluestone#28]
如题
同一个文件，如果在本地，是不会发生的
但是，如果这个文件保存在 OneDrive 的同步目录中，不管是带序号的列表还是不带序号的列表，大概率出触发这个现象：
保留一个列表内容为空（从上一个列表回车换行）时，不输入任何内容
切换到其他 APP 或者将焦点转到其他窗口，再返回此文件的编辑界面
大概率会发生跳转
测试文档见附件
[测试文档.md](https://github.com/1943time/bluestone/files/13896682/default.md)
问题避免方法：每次从其他 APP 复制了内容后，在本文档换行粘贴，不保留空白列表项，即可避免
严重性不大，估计排错很麻烦

**Comment by 1943time** [comment]
这个我加一下配置项，停止监听外部文件变动，你可以在下个版本试一下，onedrive可能会触发文件的变动。
