### ISSUE TITLE
体验优化

### ISSUE THREAD

**Issue by ignorantshr** [1943time/bluestone#30]
体验了两天，发现了几个基础性 bug，希望作者能修复一下。环境是 macOS 14.2.1，bluestone 版本 1.5.2。

- 标题快捷键偶尔不可用，无法触发
- 从其它应用切回软件的时候，文档就从上次编辑或查看位置滚动到开头，经常发生，体验很差
- 渲染不及时，像一些加粗、数学公式等并不是立即渲染，不知道什么时候才会渲染

**Comment by ignorantshr** [comment]
如果手动输入一些格式语法，并不会立即渲染
<img width="288" alt="image" src="https://github.com/1943time/bluestone/assets/34914892/db46dc26-93c7-4ca2-b9d6-24244cbd5edd">

**Comment by 1943time** [comment]
青石使用了富文本，暂不能在符号与格式之间来回转换，目前仅可以通过最后一个字符来转换格式。  
参考文档 >> [格式](https://doc.bluemd.me/book/zh-docs/markdown#%E6%A0%BC%E5%BC%8F)  
行内公式下个版本才可以通过最后一个`$`来转换，目前先使用快捷键

**Comment by 1943time** [comment]
新版已发，标题问题后续我会留意，这个问题先关闭了
