### ISSUE TITLE
Opening this file type is not currently supported while open an html file

### ISSUE THREAD

**Issue by wangxiaokun** [1943time/bluestone#32]
Sometimes, I save some HTML files. 
When I use Bluestone to open the HTML files, it tells me [ Opening this file type is not currently supported while open a html file ]
Because this function **mediaType** does not handle HTML files.
<img width="1004" alt="Snipaste_2024-01-16_15-41-47" src="https://github.com/1943time/bluestone/assets/12747757/6dc02237-bc25-48fa-9c5d-bed162262365">
I processed it, and everything is fine now.
<img width="982" alt="Snipaste_2024-01-16_15-43-36" src="https://github.com/1943time/bluestone/assets/12747757/3318f59f-3a88-448c-8841-72d853fbfd7b">
So, Do you think it's necessary to handle this?

**Comment by 1943time** [comment]
Do you want to directly display HTML content in the editor? This can be added to the next version.

**Comment by wangxiaokun** [comment]
> Do you want to directly display HTML content in the editor? This can be added to the next version.

YES, cause url link may become invalid, sometimes I save web pages  locally, just like I have saved many PDF e-books locally.

**Comment by wangxiaokun** [comment]
> Do you want to directly display HTML content in the editor? This can be added to the next version.

哈哈哈哈，老哥，才发现咱是一家人哎！

**Comment by 1943time** [comment]
我这头像不是一眼国人嘛😅

**Comment by 1943time** [comment]
新版已发不，这个问题我关闭了
