### ISSUE TITLE
[Suggestion] 还是关于ArchLinux打包运行问题

### ISSUE THREAD

**Issue by zxp19821005** [1943time/bluestone#34]
如题。
根据ArchLinux的nodejs/electron相关打包准则，尽量分离electron，因为ArchLinux AUR已经有打包好的各个版本的Electron，同时Extra之类的仓库中也会包含主流的Electron版本。
我在尝试调用系统自带的`electron22`运行app.asar文件后，软件可以打开，但是点击任何菜单都无法使用。
具体命令如下：
```
env PATH="./:$PATH" ELECTRON_IS_DEV=0 NODE_ENV=production electron22 app.asar
```
终端运行结果：
```
libpng warning: iCCP: known incorrect sRGB profile
```
不知道是否还需要添加什么别的启动参数？

**Comment by 1943time** [comment]
你的意思是linux已经包含了各个版本的electron，所以不需要如此大的安装包，你提取了其中的程序部分？Linux我仅用它当web服务器来使用，其他的不太清楚，这块恐怕不能帮到你，或者有什么可以给linux直接下发asar的指引嘛。

**Comment by zxp19821005** [comment]
是的。那我再看看吧，暂时就先用整个包吧。
