### ISSUE TITLE
how to build the web server

### ISSUE THREAD

**Issue by nzcv** [1943time/bluestone#35]
i want to use it with online how to build it? very thanks

**Comment by 1943time** [comment]
You can refer to the document link https://doc.bluemd.me/book/docs/service, This question is a bit vague. If you encounter any other detailed questions, please leave a message here

**Comment by 1943time** [comment]
At present, the editor does not support the online version. The web version is only for demonstration use and does not have the capability to be used in a production environment

**Comment by bolavefasfas** [comment]
> At present, the editor does not support the online version. The web version is only for demonstration use and does not have the capability to be used in a production environment


I understand that the notes are in markdown.md format, which is great for version control and collaboration. To facilitate online usage, we are considering a setup where changes to the notes can be automatically pushed to a GitHub repository. This repository could then be connected to Cloudflare Pages for web publishing, providing a user-friendly web server interface for viewing the notes.

Alternatively, we could also consider using a single Docker Compose setup to achieve similar functionality. This would allow us to define and run a containered Docker application, which could include both the web server to publish notes.
Why docker as the docker application will be running on a vps 24/7 for publishing as we cant keep our laptops/pc running 24/7.

I would appreciate any thoughts or suggestions on these approaches. Thank you.

**Comment by 1943time** [comment]
This requirement may be beyond the scope of the problem that Bluestone wants to solve. My understanding is that you would like to edit the Markdown document in the same repository and use Cloudflare pages to automatically publish it. What kind of problem do you want Bluestone to solve in this process? If you are a mainland Chinese user, you can add me for WeChat communication `hj0508_geek`.
