### ISSUE TITLE
In MacOS, command + W does not close the last tab

### ISSUE THREAD

**Issue by chen-yingfa** [1943time/bluestone#36]
In MacOS, command + W can close a tab, but when there is only one document open, nothing happens. In most editors, such as Obsidian and Typora, this hotkey closes the application, which is the feature that I request.

**Comment by 1943time** [comment]
command+w closing the window may result in misoperation, I am still considering this operation.

**Comment by 1943time** [comment]
I have modified it to use mod+w to close the current window when there is only one tab
