### ISSUE TITLE
Documentation/guide for contribution?

### ISSUE THREAD

**Issue by chen-yingfa** [1943time/bluestone#37]
Hi, I love this application and would like to contribute. Is there any guide for doing so? (e.g, the CONTRIBUTING.md file in other repos)

**Comment by 1943time** [comment]
Thank you for your support, Due to the large initial workload and the lack of construction in this area, there are also few annotations in the project, which requires me to prepare some time.

**Comment by chen-yingfa** [comment]
Ok thank you, I hope I can contribute as soon as possible :)

In the meantime, is there any Discord servers for this project? Opening a new issue for every problem is a bit tedious.

**Comment by 1943time** [comment]
> Ok thank you, I hope I can contribute as soon as possible :)
> 
> In the meantime, is there any Discord servers for this project? Opening a new issue for every problem is a bit tedious.

At present, the number of users of the editor is relatively small. Let's temporarily use issues to solve the problem.

**Comment by 1943time** [comment]
Unlike other projects, my expectation for this project is that it is simple, aesthetically pleasing, and easy to use. I don't really want it to become a very feature rich giant editor, and I am not very sure about the future direction of the editor. Therefore, I cannot invite other contributors to participate at this time. Thank you very much for your kindness, and I will do my best to meet your needs within Bluestone's target range.
