### ISSUE TITLE
Tooltip for hotkeys

### ISSUE THREAD

**Issue by chen-yingfa** [1943time/bluestone#38]
When hovering some button that has a corresponding hotkey, I would like the hotkey to be shown with a tooltip because I often forget the hotkey. For instance, in the popup menu below:

<img width="263" alt="image" src="https://github.com/1943time/bluestone/assets/54496664/468ef8fb-8142-4d55-be58-733317baeca5">

I wish there were a popup tooltip that shows the corresponding hotkey above my cursor when I hover over each of these buttons.

**Comment by 1943time** [comment]
This feature has been added and will be available in the next version
