### ISSUE TITLE
支持页面内跳转功能

### ISSUE THREAD

**Issue by pencilheart** [1943time/bluestone#4]
感谢作者大大，非常好用的markdown记录软件！

有个小请求，希望可以支持页面内跳转功能。比如`[跳转至二级标题](##二级标题)`。

**Comment by 1943time** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    感谢反馈，可以支持，会在下个或者下下个版本加入该功能。
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1943dejavu
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年10月25日 17:49
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              [1943time/bluestone] 支持页面内跳转功能 (Issue #4)
        
      
    
  
  
感谢作者大大，非常好用的markdown记录软件！
有个小请求，希望可以支持页面内跳转功能。比如[跳转至二级标题](##二级标题)。

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by pencilheart** [comment]
问题3: 换行后应是纯文本，但仍然保留之前的超链接

https://github.com/1943time/bluestone/assets/61617063/adc4f385-358a-45cf-8564-f0cccfad6808

**Comment by pencilheart** [comment]
问题4:
中文输入法输入英文并回车后跳转到上一行




https://github.com/1943time/bluestone/assets/61617063/6930a08f-60b7-40a1-a0ed-1ed9690c2423

**Comment by 1943time** [comment]
> 问题3: 换行后应是纯文本，但仍然保留之前的超链接
> 
>  Screen-2023-10-25-204925.1.mp4

换行保留链接我试了几次没有复现，能讲一下具体复现步骤嘛
双击选中链接其他编辑器貌似也没有这么实现，这个功能还得再考虑一下

**Comment by pencilheart** [comment]
1. 打开“测试.md”；
2. 在“INNA播放器”前回车；
3. 光标移至新的空行；
4. 输入”Bluestone“。

[测试.md](https://github.com/1943time/bluestone/files/13171856/default.md)

**Comment by 1943time** [comment]
此issues下提出的问题已全部修复，发布在v0.11.0版本，hash锚点在下个版本加入自动补全，hash锚点也可以定位到其他文件下
比如 `../dir/demo.md#head`

**Comment by 1943time** [comment]
如果你使用mac store版本，需要等待审核1-3天才会发布

**Comment by pencilheart** [comment]
> 还有一个小问题：在编辑超链接时，必须选中全部的链接文本再设置url才能实现更换此文本的链接。
> 
> 举个例子：
> 
> 1. <img alt="image" width="253" src="https://user-images.githubusercontent.com/61617063/278006543-74dbd839-a619-4671-bf6a-46838bd32022.png">
> 2. 比如在“知乎”这个链接文本上右键，选中的只有“乎”这个字，现在删除弹窗中的链接，将只删除“乎”的链接，而“知”上仍有此前链接。
> 3. <img alt="image" width="95" src="https://user-images.githubusercontent.com/61617063/278007066-817520f3-d964-4489-9714-db1085105a31.png">
> 
> **_是否可以设置为在链接文本处随意右键即选中已存在的链接，而不是仅仅链接文本中的单个字符？_**

感谢作者大大，其余bug全部已修复好。此问题还未完全解决。

若链接文本是中文，无法选择全部字符。例如：右键“指令库”只能选择“指令”二字。

![Xnip2023-10-30_16-19-37](https://github.com/1943time/bluestone/assets/61617063/ae3fc4e8-1c74-4526-b987-70b6bbed91b6)

**Comment by 1943time** [comment]
> > 还有一个小问题：在编辑超链接时，必须选中全部的链接文本再设置url才能实现更换此文本的链接。
> > 举个例子：
> > 
> > 1. <img alt="image" width="253" src="https://user-images.githubusercontent.com/61617063/278006543-74dbd839-a619-4671-bf6a-46838bd32022.png">
> > 2. 比如在“知乎”这个链接文本上右键，选中的只有“乎”这个字，现在删除弹窗中的链接，将只删除“乎”的链接，而“知”上仍有此前链接。
> > 3. <img alt="image" width="95" src="https://user-images.githubusercontent.com/61617063/278007066-817520f3-d964-4489-9714-db1085105a31.png">
> > 
> > **_是否可以设置为在链接文本处随意右键即选中已存在的链接，而不是仅仅链接文本中的单个字符？_**
> 
> 感谢作者大大，其余bug全部已修复好。此问题还未完全解决。
> 
> 若链接文本是中文，无法选择全部字符。例如：右键“指令库”只能选择“指令”二字。
> 
> ![Xnip2023-10-30_16-19-37](https://user-images.githubusercontent.com/61617063/278983519-ae3fc4e8-1c74-4526-b987-70b6bbed91b6.jpg)

右键操作与table中的操作冲突，下个版本可以尝试加入双击选中链接，感谢反馈。
