### ISSUE TITLE
Option + arrow keys does not work inside code blocks in MacOS

### ISSUE THREAD

**Issue by chen-yingfa** [1943time/bluestone#41]
In MacOS, when the caret is in a code block, pressing Option + arrow keys only moves one character at a time, while the default behavior in most editors is to move one word at a time.

**Comment by 1943time** [comment]
![Kapture 2024-01-22 at 13 35 36](https://github.com/1943time/bluestone/assets/115093678/3f73d75b-b35f-4a1b-8948-0207d9b8a1f4)
Are you referring to the situation in the image? I did not reproduce this issue
