### ISSUE TITLE
"move to trash" doesn't work.

### ISSUE THREAD

**Issue by yu2chuan** [1943time/bluestone#42]
After picking a md file, I chosed "move to trash" and then the program crashed.
I started the program again. But the md file I wanted to remov is still there.

**Comment by 1943time** [comment]
Is this accidental? Did you check the `Out of focus detection Markdown` option? There are currently some bugs in this option.

**Comment by yu2chuan** [comment]
No matter the option is checked or not, the program always crashed when I moved the md file to trash.

**Comment by 1943time** [comment]
I'm sorry I can't reproduce this issue here. Deleting files here won't cause a crash. I can only guess where the problem is in the code and capture it.

**Comment by yu2chuan** [comment]
I tried to send the different files to trash. The program still crashed on my Windows 10. Any crash log generated by bluestone?

**Comment by 1943time** [comment]
At present, there is no error log written. It will be added in the next version. Would it be convenient to provide me with a screenshot of the console log, as shown in the figure

<img width="1446" alt="image" src="https://github.com/1943time/bluestone/assets/115093678/10ddd4af-c601-4998-b19e-2b4f77a358ed">

Open the console when you delete again，It is in `View -> toggle developer tools` . Are you using version 0.13.0?

**Comment by yu2chuan** [comment]
https://drive.google.com/uc?id=1AWjWunI-OpN1id0QOyVssczgBhWq2MF8

**Comment by 1943time** [comment]
> https://drive.google.com/uc?id=1AWjWunI-OpN1id0QOyVssczgBhWq2MF8

This issue has been fixed, but I did not use it to reproduce the deletion crash issue, so I cannot guarantee that the next version will solve it.
