### ISSUE TITLE
Caret position after the closing `$` in inline math

### ISSUE THREAD

**Issue by chen-yingfa** [1943time/bluestone#43]
I wish that after enter the closing `$`, the caret position should be placed after this character, but currently the caret is positioned before the closing `$`.

**Comment by chen-yingfa** [comment]
I get your reason, but I think this behavior is undesirable because most editors place the caret after the closing character (e.g., Typora and Obsidian). I think if the user enters a `$`, the user likely knows that it causes a conversion. At least, is it possible to have an option for the user to choose to place the caret after the closing `$`?

**Comment by 1943time** [comment]
I can add this feature first, but I think it will cause some trouble for people who don't use inline formulas. In future versions, I will convert in line formulas to configurable items
