### ISSUE TITLE
Option to change the default letter style in math

### ISSUE THREAD

**Issue by chen-yingfa** [1943time/bluestone#44]
Most Latex renderers use italic font by default, but Bluestone currently uses non-italic, as shown below.

<img width="187" alt="image" src="https://github.com/1943time/bluestone/assets/54496664/ea393fc9-0df6-46a6-84d4-8a314f4a09ee">

I hope that there is an option to change the default font so that the render result is consistent with other renderers.

**Comment by 1943time** [comment]
Solved, next version will be released
