### ISSUE TITLE
Untitled files

### ISSUE THREAD

**Issue by chen-yingfa** [1943time/bluestone#47]
In many editors, we can input content in "Untitled files" by pressing `mod + N`. Can we do that in Bluestone?

**Comment by 1943time** [comment]
Bluestone can use `mod+n` to directly create files

**Comment by chen-yingfa** [comment]
Doesn't Bluestone require the file to be named before creation? I want to create a file without name, and only choose a name upon save, like VSCode.

**Comment by 1943time** [comment]
I understand what you mean. I will add this feature in future versions, but I cannot confirm the time at the moment.
