### ISSUE TITLE
"source" mode

### ISSUE THREAD

**Issue by chen-yingfa** [1943time/bluestone#49]
Is there a "source" mode as in Typora such that we can directly edit the source text instead of the rendered one?

**Comment by 1943time** [comment]
The source code mode is a relatively large feature that should be added in the future, but it requires some research and development time

**Comment by 1943time** [comment]
Unfortunately, after consideration, it was finally decided that the source code mode is not the development goal of this project and is not supported for the time being.

**Comment by GwynethLlewelyn** [comment]
Such a pity! I was just going to uninstall Joplin + Typora, which I use every day for taking notes and having them organised and sync'ed. Inkdown is so much better at doing basic things, and it's superfast, compared to those other tools.
But, alas, it seems that the way I'd love to use Inkdown is not aligned with this project's ultimate goal...

**Comment by 1943time** [comment]
> Such a pity! I was just going to uninstall Joplin + Typora, which I use every day for taking notes and having them organised and sync'ed. Inkdown is so much better at doing basic things, and it's superfast, compared to those other tools. But, alas, it seems that the way I'd love to use Inkdown is not aligned with this project's ultimate goal...

Thank you for your recognition, Inkdown is essentially not a Markdown centric editor, it only uses Markdown as a carrier because Markdown is a universal format. Inkdown aims to better read and publish documents, while striving to maintain document universality.
