### ISSUE TITLE
2 bugs and 2 feature

### ISSUE THREAD

**Issue by DarkFlameMasterDev** [1943time/bluestone#5]
#### bug:
1. when I open the line number in code block, the Front matter will be hided
	<img width="472" alt="image" src="https://github.com/1943time/bluestone/assets/36620503/60a67ca1-4c83-44d3-bb82-ad661a4d4613">
2. the code in line will wrap 
	<img width="822" alt="image" src="https://github.com/1943time/bluestone/assets/36620503/bc047322-44d7-448e-8a3e-e191bab9e2ff">

#### feature
1. wish the image url input field can be always be the longest state
2. wish users can choose wether the default local image url is relative path or absolute path
<img width="440" alt="image" src="https://github.com/1943time/bluestone/assets/36620503/7fb2484c-588a-4869-950c-faeb38eab122">
<img width="467" alt="image" src="https://github.com/1943time/bluestone/assets/36620503/5a714dd8-e360-4b24-ba07-585405fa6467">

**Comment by 1943time** [comment]
Other problems should be fixed in the next version. If Image inserts a local picture, if you insert a picture in an open folder, it will automatically insert it with a relative path. Can this solve your problem? I can't think of other scenarios that require configuring relative or absolute paths.

**Comment by 1943time** [comment]
Other problems should be fixed in the next version. If Image inserts a local image, if you insert a image in an open folder, it will automatically insert it with a relative path. Can this solve your problem? I can't think of other scenarios that require configuring relative or absolute paths.

**Comment by 1943time** [comment]
- fix display front matter
- Inline Code automatic line wrapping can cause new problems. If you need inline code line wrapping, you can use cmd+enter to wrap within the paragraph
- Added the width of the image path input box
- When importing local images, if the image is in the open folder, use a relative path.

The above modifications will be released in the next version
