### ISSUE TITLE
Command Palette

### ISSUE THREAD

**Issue by chen-yingfa** [1943time/bluestone#51]
Is it possible to add a command palette such as in Obsidian and VS Code (`cmd + shift + P`)? It is much more convenient than navigating through the settings or remembering all hotkeys.

**Comment by 1943time** [comment]
Experience upgrade features will not be added immediately, and there are still some core features in bluestone that are being improved

**Comment by 1943time** [comment]
At present, I have not found any operations that are more suitable for the command palette to operate, so I have closed it first. If you find a scenario where using the command palette to operate more quickly, you can leave a message here.
