### ISSUE TITLE
共享服务容器化

### ISSUE THREAD

**Issue by leookun** [1943time/bluestone#55]
很赞的项目，共享服务可以考虑添加容器化支持吗。不想在宿主机安装服务，我可以提交pr

**Comment by 1943time** [comment]
你好，我对容器不是很熟悉，你这边能改造也可以，保持主机安装能力就行。

**Comment by leookun** [comment]
> 你好，我对容器不是很熟悉，你这边能改造也可以，保持主机安装能力就行。

https://github.com/1943time/bluestone-service/pull/2
