### ISSUE TITLE
support photo on the cloud?

### ISSUE THREAD

**Issue by yu2chuan** [1943time/bluestone#57]
is it possible to show the photo on the cloud?
for example
https://drive.google.com/uc?id=1a-ILm1x-icyQcZS3QH4yg6tDniKujmZm

**Comment by 1943time** [comment]
I don't quite understand this feature. Is there any other editor that has been implemented as a reference?

**Comment by yu2chuan** [comment]
On the notepads (https://github.com/0x7c13/Notepads), it can support ![](hyperlink). But bluestone seems not to support this. For example: ![](https://drive.google.com/uc?id=1a-ILm1x-icyQcZS3QH4yg6tDniKujmZm)

**Comment by 1943time** [comment]
Do you mean to insert a network image? You can use the `mod+p` key, then enter the network image address, or input`![] (link)` is converted to an image through the last `)` symbol.

**Comment by 1943time** [comment]
> I think if support PicList(A fork of PicGo) for image upload.it would be wonderful!
> 
> Reference: [marktext/marktext#2460](https://github.com/marktext/marktext/issues/2460) [typora/typora-issues#2476](https://github.com/typora/typora-issues/issues/2476) https://github.com/Kuingsmile/PicList

PicList support added to v0.14.0

**Comment by yu2chuan** [comment]
I can't wait to try this.
