### ISSUE TITLE
Add intergration of image-bed tools

### ISSUE THREAD

**Issue by Jordan-Haidee** [1943time/bluestone#59]
In Typora, an image can be uploaded to clouds automatically via image-bed tools, if it is pasted from clipboard. It is nice and expected that bluestone can add intergration of `PicGo/PicList` 😋.<br>
![image](https://github.com/1943time/bluestone/assets/85778126/231d8485-9057-4431-9685-67c4676f384e)

**Comment by 1943time** [comment]
I have not yet used this software. In future versions, I will go back to learn about its usage and consider adding it.

**Comment by 1943time** [comment]
PicList support added to v0.14.0
