### ISSUE TITLE
自动粘贴重复内容

### ISSUE THREAD

**Issue by ignorantshr** [1943time/bluestone#61]
输入完毕之后再点击鼠标，会出现自动粘贴重复内容，偶发。
<img width="808" alt="image" src="https://github.com/1943time/bluestone/assets/34914892/d620bcb4-c3cd-423e-8c17-a8285de97e6c">

**Comment by ignorantshr** [comment]
版本 1.6.3，macOS 14.3

**Comment by 1943time** [comment]
过年事情较多，没有看issues,我没有复现这个问题，如果有更准确的复现步骤，在这里留言。
