### ISSUE TITLE
remote media

### ISSUE THREAD

**Issue by yu2chuan** [1943time/bluestone#64]
it's great thing to see the new version with new UI.
I pasted this "https://drive.google.com/uc?id=1j573vmWzgXQOAp2Rr1y1XAdhfO95O4Qo" in the remote media.
But it just looks like a higherlink, not showing photos in the editor. is it what the remote media feature should be?

**Comment by 1943time** [comment]
Currently, the suffix name is used to determine whether it is an image file. There is no suffix name in this link, and this issue will be fixed in the next version

**Comment by 1943time** [comment]
This link has access restrictions on the server, so it cannot be inserted using a link. You can use the download option in Insert Remote Media to download to your local device first.

**Comment by yu2chuan** [comment]
After following your suggestion for a while, I want to read my note/data on any device. So I still expect inkdown or bluestone can show photos shared by google drive links. Is it possible to make the program attempt to show photos when this pattern, "drive.google.com/uc?id=" can be sensed by the inkdown/bluestone.

**Comment by 1943time** [comment]
This link has been denied access by Google. I can try using iframe to display it in the next version, but I cannot guarantee its validity. The next version will take some time

**Comment by yu2chuan** [comment]
If possible, you can put an image shared to everyone on google drive for this test.

**Comment by 1943time** [comment]
> If possible, you can put an image shared to everyone on google drive for this test.

After some attempts, it was found that Google Drive files require special network processing before they can be displayed. As a general editor, inkdown cannot add optimization code for special links, and this feature is currently not supported. At present, the only way to achieve this is to right-click and copy the image in the browser, and then paste it into the editor.
