### ISSUE TITLE
Docker compose file to deploy it on a homeserver/vps  {Feature Request}

### ISSUE THREAD

**Issue by bolavefasfas** [1943time/bluestone#66]
App is great I want my notes synced to all my devices thats possible if its a webapp or I can access via browser like outline/affine selfhosted versions 

## Solution
Need a docker compose for the app

Or a way to sync notes accross devices 
like mobile and pc 

if it was just pc I would have used syncthing and thats all but thats not the case.

And I dont understand why this app has less stars its great.Havent you publishes this project on producthunt, alternative io and other places ?

Thanks

**Comment by 1943time** [comment]
Thank you for your recognition. I think the editor is not yet perfect, so there hasn't been much promotion.

Do you want to be able to edit your notes on both mobile and web platforms and synchronize them with each other?

The workload of this feature is still considerable, and I can consider developing it in the future.

But there is no guarantee that this feature will be free and open source. I hope you can understand the open-source author.

I am not very familiar with Docker technology, so I will find time to delve deeper into it.

**Comment by bolavefasfas** [comment]
## 1. Do you want to be able to edit your notes on both mobile and web platforms and synchronize them with each other?

**Yes**

## 2. But there is no guarantee that this feature will be free and open source. I hope you can understand the open-source author.

**one time fees would be great at affordable price like [typora.io](https://typora.io/)**

## 3. I am not very familiar with Docker technology, so I will find time to delve deeper into it.

**Please take a look at docker, it will ease the deploymoent of the publish webserver a lot I will try to contanarise it myself though.**

**Comment by 1943time** [comment]
Currently I'm also making the editor more stable. The web version may take some time. You can follow subsequent project updates~.

**Comment by bolavefasfas** [comment]
> Currently I'm still making the editor more stable. The web version may take some time. You can follow subsequent project updates~.

 coudnt find docs on how to host the webserver for publishing From app if i open it says page not found can you send wiki link

**Comment by 1943time** [comment]
https://doc.bluemd.me/book/docs/Network%20Service
However, the release program will soon undergo refactoring, and there may be a break change in the future. The project address is https://github.com/1943time/bluestone-service A contributor has added Docker support, but I am not very familiar with Docker. You can check it out

**Comment by bolavefasfas** [comment]
> https://doc.bluemd.me/book/docs/Network%20Service However, the release program will soon undergo refactoring, and there may be a break change in the future. The project address is https://github.com/1943time/bluestone-service A contributor has added Docker support, but I am not very familiar with Docker. You can check it out

Amazing I will use the base docker file and develope a docker compose file and add readme file.

**Comment by 1943time** [comment]
@bolavefasfas 
The sharing program has adapted to the new version of the editor and can now be used https://doc.bluemd.me/doc/tAfxJPwODVe4i#sharing-service

**Comment by bolavefasfas** [comment]
> @bolavefasfas The sharing program has adapted to the new version of the editor and can now be used https://doc.bluemd.me/doc/tAfxJPwODVe4i#sharing-service

# Bluestone Service Deployment

I have successfully deployed the Bluestone service using the provided Dockerfile from the official repository (<https://github.com/1943time/bluestone-service>). To streamline the deployment process, I have added a `docker-compose.yml` file to complement the existing Dockerfile. This addition was necessary due to the absence of deployment instructions in the original repository.

After thoroughly testing the deployment, I have submitted a pull request to contribute the `docker-compose.yml` file back to the project.

The following image demonstrates the Bluestone service running within a Docker container:

![Bluestone Service in Docker Container](https://github.com/1943time/bluestone/assets/82230241/e0eeaf27-0323-4552-b819-0070c0330261)

---

## Deployment Instructions

To deploy the Bluestone service, follow these steps:

1. Clone the repository:

```bash
git clone https://github.com/1943time/bluestone-service && cd bluestone-service
```

2. Before proceeding, ensure you have Docker installed on your system. You can install Docker using the following command:

```bash
sudo apt update -y ; sudo apt install docker-compose -y
```

3. Add docker-compose.yml if its missing 
```
version: "3.9"
services:
  bluestone:
    container_name: bluestone-service
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "3002:3002"
    restart: always

```
4. Build and run the Docker container using `docker-compose`.


<details open>
<summary>Using the faster docker-compose syntax (older)</summary>

```bash
sudo docker-compose up --build
```

</details>

OR 

<details>
<summary>Using the latest docker compose syntax</summary>

To use the latest `docker compose` syntax, refer to the official documentation at <https://docs.docker.com/compose/install/> for installation instructions.

```bash
sudo docker compose up --build
```

</details>

## Exposing Bluestone Service

To expose the Bluestone service, choose one of the following methods:

<details>
<summary>Nginx Proxy Manager</summary>

1. Ensure you have Nginx Proxy Manager installed and running on your system.
2. Access the Nginx Proxy Manager dashboard and create a new Proxy Host.
3. Enter the desired domain name for the Bluestone service and set the forward hostname to the IP address of your Docker host.
4. Set the forward port to `3002` (the default Bluestone service port).
5. Save the configuration and test the domain to access the Bluestone service.

</details>

<details>
<summary>Nginx</summary>

1. Ensure you have Nginx installed on your system.
2. Create a new Nginx server block configuration file (e.g., `/etc/nginx/sites-available/bluestone.conf`).
3. Add the following configuration to the file, replacing `your_domain.com` with the desired domain name:

```nginx
server {
    listen 80;
    server_name your_domain.com;

    location / {
        proxy_pass http://docker_host_ip:3002;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

4. Create a symbolic link to enable the configuration:

```bash
sudo ln -s /etc/nginx/sites-available/bluestone.conf /etc/nginx/sites-enabled/
```

5. Test the Nginx configuration and reload the service:

```bash
sudo nginx -t && sudo systemctl reload nginx
```

6. Test the domain to access the Bluestone service.

</details>

The Bluestone service has been tested and verified to work with various domain exposure methods, including Cloudflare Tunnels, Tailscale Funnel, and Traefik.

**Comment by 1943time** [comment]
Thank you very much for adding docker support.
