### ISSUE TITLE
Clicking somewhere in the doc moves focus to beginning/end

### ISSUE THREAD

**Issue by zareith** [1943time/bluestone#67]
Hello Jie,

Thanks for creating and maintaining this app. I have been using this for the last few months after trying out a couple of other apps and found the Wysiwyg interface to be really nice for my work. 

I am also probably the only person who uses your app for writing a fantasy novel. So I often work with very long documents. 

One inconvenience I frequently face is that when the editor is not focused, and I click somewhere in the middle of document, sometimes (but not always, and not predictably) the editor scrolls to either the beginning of the document or the end. So during editing, I often find myself loosing my position and it takes some time before I find where I was again. 

I understand that my use case may be somewhat different from what you intended for this app, but I would appreciate if this were to be addressed.

**Comment by 1943time** [comment]
When this situation occurs, did you switch to selecting media elements? If you could find more accurate reproduction steps, it would be easier for me to troubleshoot. In occasional scenarios, it would be difficult for me to identify the problem.

**Comment by zareith** [comment]
I don't have media elements, if it helps here is a sequence that seems to be resulting in unexpected navigation most of the times. 


https://github.com/1943time/bluestone/assets/146206208/0111068a-a8b0-4284-a675-c8350e92a4ba

Step 1: I focus on the codeblock for yaml frontmatter at the top
Step 2: I use the sidebar to navigate to the glossary list in the very bottom
Step 3: I click on the first bullet point of the glossary
Step 4: The UI automatically scrolls to the top (I am assuming to the codeblock that was initially focused)

**Comment by 1943time** [comment]
Thank you for raising the question. I think I have a rough idea of the problem and it will be fixed in the next version.

**Comment by 1943time** [comment]
Your article has a lot of words. Do you consider splitting it into multiple files because there is currently no good way to optimize long texts? Have you felt any typing delay?

**Comment by zareith** [comment]
Thanks a lot. 

Yes, splitting to multiple docs is something I am planning to do. However, when I write I usually don't have a clear separation of chapters or sequence of events in mind and I do the organization and splitting later - so having the whole thing in the same doc is convenient when starting out.

I see absolutely no performance issues. It was one of the reasons I started using bluestone - some of the other editors I tried would freeze up or hang, where as with bluestone the experience is very smooth.

**Comment by 1943time** [comment]
In the scenario I tested, over 100000 characters may experience a slight typing delay. If you don't have this feeling on your end, that's great. I will find ways to optimize the performance of long texts in the future, but currently this is not my main goal.
