### ISSUE TITLE
Ctrl+A can not be used to select all the text

### ISSUE THREAD

**Issue by zareith** [1943time/bluestone#68]
In the search box, if I press Ctrl+A to select the previous search query, nothing happens.

**Comment by 1943time** [comment]
I don't quite understand this question. Can you describe it more accurately or add screenshots or videos?

**Comment by zareith** [comment]
Yes, please take a look at the video below: 

1. I press ctrl+f which shows the search field and focuses it
2. I press ctrl+a to select the previous search result, nothing happens. In the search input field ctrl+a doesn't seem to work. 

[Screencast from 2024-03-15 13-19-24.webm](https://github.com/1943time/bluestone/assets/146206208/47982147-b260-40d8-b511-fa516fc0a4a2)

If it helps, I am using it on Ubuntu (Mantic) through the AppImage.

**Comment by 1943time** [comment]
The editor did not add the logic to return the previous search result with ctrl+a. Is this the behavior of other editors? Or the feature you want is to use the hotkey ctrl+a to return the previous search result？

**Comment by 1943time** [comment]
Do you only want to use ctrl+a to select all text in the input box, so that it conforms to the browser's default behavior? This issue has been resolved, please wait for the next version.

**Comment by zareith** [comment]
Ok, that's great. Thanks again.
