### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by 2545504198** [1943time/bluestone#69]
首先感谢开发此编辑器，体验之后有部分建议请参考
1. 增加链接跳转
2. 切换为源代码功能
3. 增加部分快捷键，如加粗Ctrl+B，斜体Ctrl+I之类的

**Comment by 1943time** [comment]
1. 链接跳转具体指什么呢，目前链接支持跳转文件路径和http链接
2. 源代码模式非青石的开发目标，所以暂时没有计划支持
3. 在浮动栏上鼠标停留会显示加粗等快捷键，前提是需要选中文字，在改变文字格式后使用esc关闭浮动栏会导致bug，先不要使用esc关闭浮动栏

**Comment by 2545504198** [comment]
1. a链接的跳转，发现按着ctrl+单机可以打开浏览器打开，但是没有提示，包括手鼠标
2. 切换成源代码编辑可以微调修改，切换成txt编辑器也可以
3. 浮窗是可以操作，但是增加了操作复杂度，还要先选中才能操作，需要鼠标参与

**Comment by 1943time** [comment]
<img width="603" alt="image" src="https://github.com/1943time/bluestone/assets/115093678/5f1cf5d8-e46a-4222-a7f4-90574ae13a72">

- 在浮动栏上悬停，可以查看快捷键，如果不选中文字，加粗的话怎么知道你想加粗哪部分文字呢？
- 鼠标选停在链接上超过2秒钟大概会出现提示文字，只是比较慢。
- 不能草率的添加功能，比如txt这样，每个功能应该有其可用性和必要性 
 https://doc.bluemd.me/doc/Q1vCjNmL8Dnvz#%E7%A2%8E%E7%A2%8E%E5%BF%B5 我在这里解释了为什么不希望青石加入过多的功能
