### ISSUE TITLE
location problem after link

### ISSUE THREAD

**Issue by pencilheart** [1943time/bluestone#7]
https://github.com/1943time/bluestone/assets/61617063/5557389f-f4a6-4a1e-bea3-48d3710506d2

https://github.com/1943time/bluestone/assets/61617063/bcec78ca-fee7-4b4d-be9f-b25647e67db8

**As shown, typing after link will be wrong.**

https://github.com/1943time/bluestone/assets/61617063/ea6f420c-9fb4-466b-8542-8f686394bd9c

**Then I found that there is a unvisible space after link.**

How can we avoid this?

**Comment by 1943time** [comment]
This space does not really exist. It is used to help you use the arrow keys to break out of the link format and does not affect the output of markdown text.

**Comment by pencilheart** [comment]
Fine, thx.
