### ISSUE TITLE
一些优化建议

### ISSUE THREAD

**Issue by UICO32** [1943time/bluestone#70]
作者大大，使用了一段时间后有些建议，辛苦看一下~

- win上面链接似乎无法通过ctrl+click打开（没反应）
![image](https://github.com/1943time/bluestone/assets/109026944/901ed055-17e8-4bf7-bd3a-4f331dcdd37a)
- 是否能为--- 增加一个分割线的md语法？（目前快捷键有些隐蔽、操作距离有点远）
![image](https://github.com/1943time/bluestone/assets/109026944/da8d4526-76c6-4865-85e9-0ad9c4ef7ba4)
- 图片可不可以给一个预览或者复制的功能，目前没办法复制到别的软件中
- 能否提供一个阅读位置记忆的功能/多标签页的功能，目前切换到别的文档返回后就丢失位置了，所以在长文写作中有些难受

**Comment by 1943time** [comment]
- 无法通过ctrl+click打开链接是一个严重的问题，我在之前的测试中没有遇到，是否可能有其他软件拦截了快捷键？
- 现在就可以使用三个- 加回车来插入分割线。
- 由于electron的限制图片只能复制jpg和png格式，所以是有缺失的，下个版本可以在图片上加入 Reveal in File Explorer 的菜单，再从系统文件复制
- 多标签页现在就是支持的，返回丢失我没理解是什么场景，可以再描述详细一些么。

**Comment by UICO32** [comment]
感谢回复，我又测试了下：
- 第一个问题是无法打开本地url（可以打开网址链接的），但是例如obsidian://xxxxxx这种无法唤起。（如果本来就不行的话希望能支持下，链接一些文献和素材挺需要的~）
- 第二个问题是我草率了，以为是空格完成插入
- 能否再追加个右键复制为png？会更加方便些~
- 多标签页也是我草率了，没发现哈哈哈。 
返回丢失是指：我从【测试文档2】（已滚动一定位置）切换到【测试文档1】再切回来的时候，会回到文档顶部。（测试了下，siyuan会保持之前滚动的位置。不过鉴于刚发现多标签页，这个应该不算问题了..,）
![image](https://github.com/1943time/bluestone/assets/109026944/6fab5608-6293-4291-b6b4-00c2aa0ed81a)

**Comment by 1943time** [comment]
- 第一个问题下个版本解决
- 由于图片无法复制webp或其他格式，加入复制按钮会比较奇怪，所以先用再文件系统中显示代替吧

**Comment by filefi** [comment]
建议类似typora中图片导入时指定相对路径时的环境变量，方便在hexo或其他静态网页生成工具中写md时导入图片到与当前文件名相同的目录，方便统一管理图片等静态资源。

**Comment by 1943time** [comment]
> 建议类似typora中图片导入时指定相对路径时的环境变量，方便在hexo或其他静态网页生成工具中写md时导入图片到与当前文件名相同的目录，方便统一管理图片等静态资源。

没太理解这个需求是什么，目前有使用相对路径保存图片的功能，导入图片是什么操作呢？

**Comment by filefi** [comment]
https://support.typora.io/Images/#when-insert-images
![image](https://github.com/1943time/bluestone/assets/16501603/62500c04-87bb-4573-881d-25d79dbd5809)
如上图，Typora预定义了一个变量`${filename}`用于引用当前md的文件名，这样就可以实现让图片资源保存的目录与引用它们的md文件保持关联。比如，我写hexo，我希望拖入图片到编辑器时，自动将图片复制到我与当前md文件名同名的目录中。这样当我迁移某个特定md时，能方便的一并迁移其引用的图片。

**Comment by 1943time** [comment]
@filefi 
<img width="703" alt="image" src="https://github.com/1943time/bluestone/assets/115093678/3dcf4abb-5300-4da2-8ad4-51ca37c76fb0">
目前可以配置使用相对路径做到这一点，你可以尝试一下

**Comment by 1943time** [comment]
@filefi 

https://github.com/1943time/bluestone/assets/115093678/06ac95dc-5db2-4249-a172-56fe1ed2d7af

我才尝试之后相对路劲存储确实有问题，新版可以使用相对路径存储，如果还是未能解决你的问题，表示遗憾，这个issues我先关闭了

**Comment by 1943time** [comment]
@UICO32 
链接问题已解决，加入了本机图片快捷打开方式。

**Comment by filefi** [comment]
> @filefi <img alt="image" width="703" src="https://private-user-images.githubusercontent.com/115093678/317592987-3dcf4abb-5300-4da2-8ad4-51ca37c76fb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2OTU2MzAsIm5iZiI6MTcxMTY5NTMzMCwicGF0aCI6Ii8xMTUwOTM2NzgvMzE3NTkyOTg3LTNkY2Y0YWJiLTUzMDAtNGRhMi04YWQ0LTUxY2EzN2M3NmZiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOVQwNjU1MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MGIyNTI0NTdmZDcwNmIxNmYyMjQ4NTRjMDIzZDE5Mjk3ZGY4NGZiYThmYjhkY2IwMTMwNmFhMWM2M2UwM2RmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wd_VVZLMN207_tZ65GnbxKF6enar5i1gCap8u6Py7RY"> 目前可以配置使用相对路径做到这一点，你可以尝试一下

你没明白，你的相对路径只能静态资源跟md放在同一个目录中，否则做不到方便的迁移特定md及其资源。例如，多个md在同一个目录中，你怎么带走其中一个md和其引用的资源呢？单独写个迁移程序解析md中的图片引用吗？而Typora增加一个变量${filename}会让图片和静态资源放置布局极大地灵活，因为有${filename}变量提供关联，我可以`./${filename}/`，可以`../static/${filename}`。

**Comment by 1943time** [comment]
@filefi 
<img width="1131" alt="image" src="https://github.com/1943time/bluestone/assets/115093678/85bc8e89-0eb3-422c-8ea8-4711f49bf6ba">
<img width="423" alt="image" src="https://github.com/1943time/bluestone/assets/115093678/c4e386f6-8224-4504-9862-3faa5f035c39">
你是指这种形式对吧，新版是可以的，不过在复制本机文件的时候文件树不会立即刷新，复制剪贴板的时候可以，发版时没注意这个问题。目前青石在成熟性上跟已有markdown还存在一些差距。

**Comment by filefi** [comment]
> @filefi <img alt="image" width="1131" src="https://private-user-images.githubusercontent.com/115093678/317997062-85bc8e89-0eb3-422c-8ea8-4711f49bf6ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MTgxMDIsIm5iZiI6MTcxMTcxNzgwMiwicGF0aCI6Ii8xMTUwOTM2NzgvMzE3OTk3MDYyLTg1YmM4ZTg5LTBlYjMtNDIyYy04ZWE4LTQ3MTFmNDliZjZiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOVQxMzEwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Y2M0YTNhM2ZkYmUzMGE2NDE5YTAxMWM4MDcyZWIyZWY2M2E2NDVhZWYzYzEzMGQ1ZWVjMzJlMjZiNjFjMjE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PJCMuxoHnKqonRGAPyeLgcGtyrRh9MYJ6C2_96gd0yI"> <img alt="image" width="423" src="https://private-user-images.githubusercontent.com/115093678/317997098-c4e386f6-8224-4504-9862-3faa5f035c39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MTgxMDIsIm5iZiI6MTcxMTcxNzgwMiwicGF0aCI6Ii8xMTUwOTM2NzgvMzE3OTk3MDk4LWM0ZTM4NmY2LTgyMjQtNDUwNC05ODYyLTNmYWE1ZjAzNWMzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOVQxMzEwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTBkZTBjNjI5OGQzMzVlMDU0ZmEwZWJlMzcyODQxZGZlNWE2N2MwNGU2MDc1NDg5NjlhYzNlZGJmNTA0NDEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nc5CVE_YIWpXUWL6A8ljOQTXeyxbrTS6yfvMXCaoUIM"> 你是指这种形式对吧，新版是可以的，不过在复制本机文件的时候文件树不会立即刷新，复制剪贴板的时候可以，发版时没注意这个问题。目前青石在成熟性上跟已有markdown还存在一些差距。

@1943time `${filename}`代表的是当前正在编辑的md文件的文件名。你用一用Typora就知道了。
