### ISSUE TITLE
Space selection issue

### ISSUE THREAD

**Issue by zareith** [1943time/bluestone#71]
Hello again, 

In the space selection dropdown, we have support for reordering using drag and drop. This sometimes causes problems.

Here in the recording, my intent is to switch to another space. 
But when I click on another item from the dropdown, the drag and drop gets activated. After that the clicked item follows the mouse indefinitely. Even if release mouse button, click outside, dismiss the menu, press escape etc. I can not get rid of the item following the mouse. 

Once this happens, it becomes impossible to use that menu to switch space afterwards, until we restart the app.

[Screencast from 2024-03-24 15-32-59.webm](https://github.com/1943time/bluestone/assets/146206208/dac7dd63-8d06-4f31-a02d-9f1227c065ee)

**Comment by 1943time** [comment]
I did not reproduce this issue after multiple tests, and I am not sure if it is related to the system. I will try again later, but the drag delay will be corrected.

**Comment by 1943time** [comment]
I still haven't reproduced this problem. Do you often encounter this problem?

**Comment by zareith** [comment]
I do face it like one out of four times, but it could be something specific to my hardware if not easy to reproduce. 

I have stopped using that menu for now, and I just keep two windows open. That is good enough for me.

**Comment by 1943time** [comment]
I have made some optimizations to drag and drop sorting, and the next version should be able to solve this problem.

**Comment by zareith** [comment]
Ok, thanks a lot 😃
