### ISSUE TITLE
[Feture Request] 打开应用时默认进入上一次退出时打开的空间

### ISSUE THREAD

**Issue by kahosan** [1943time/bluestone#73]
希望能在设置中添加标题功能的选项。

**Comment by 1943time** [comment]
> 希望能在设置中添加标题功能的选项。

这个设置用来做什么，没理解？

**Comment by kahosan** [comment]
> Owner

目前，启动应用后需要手动在这里选择一次最近打开的空间

<img width="258" alt="image" src="https://github.com/1943time/bluestone/assets/33192552/371ff401-0a84-4d52-bfb5-2dbe5af89b32">

我想节省一次操作，打开应用后直接进入上一次退出时打开的空间

**Comment by 1943time** [comment]
可以，下个版本可以添加这个配置项

**Comment by 1943time** [comment]
已加入  [commit](https://github.com/1943time/bluestone/commit/7530d02af572eee86ffc81e61b86ae2f97c792f8)
