### ISSUE TITLE
[BUG] 自动打开空间的开启后，会有一个访达的选择界面

### ISSUE THREAD

**Issue by kahosan** [1943time/bluestone#74]
如图，启动应用后会有一个访达的选择界面。
正常应该是直接打开空间。

<img width="975" alt="image" src="https://github.com/1943time/bluestone/assets/33192552/71ea0d42-3538-4163-bfab-cceb701adfde">

**Comment by 1943time** [comment]
mac store由于有严格的权限限制，所以读取会弹窗，如果你不希望他存在，可以使用非mac store版本

**Comment by kahosan** [comment]
> mac store由于有严格的权限限制，所以读取会弹窗，如果你不希望他存在，可以使用非mac store版本

原来如此，感谢回复
