### ISSUE TITLE
Spell check suggestions

### ISSUE THREAD

**Issue by zareith** [1943time/bluestone#75]
Hello again. Hope you are doing well.

When we have a spelling error, in browser textarea if we right click we get a small list of suggestions in the context menu as well as option to add the word to built in dictionary. For example:

![image](https://github.com/1943time/bluestone/assets/146206208/d7916d57-c2a6-49c6-a543-fa3e79bd4406)

In this app, the context menu seems to be suppressed so even if we enable spell check the errors are shown with red underline, but these suggestions or the option to add to dictionary are not available. 

Curious if it would be feasible to enable this or equivalent feature.

**Comment by 1943time** [comment]
<img width="619" alt="image" src="https://github.com/1943time/bluestone/assets/115093678/e43326ac-fd83-417f-98ef-4c78c2673c69">
Due to the limitations of the electron, currently only the one shown in the above image can be achieved. Can it meet your needs?

**Comment by lorefnon** [comment]
Of course, this would be perfect.

**Comment by zareith** [comment]
Definitely. This looks perfect.
