### ISSUE TITLE
Add syntax highlighting for pandoc style citations

### ISSUE THREAD

**Issue by SimonGreenhill** [1943time/bluestone#76]
Please add syntax highlight for Pandoc style citations (e.g. https://pandoc.org/chunkedhtml-demo/8.20-citation-syntax.html)

**Comment by 1943time** [comment]
Bluestone currently does not support the syntax specification of Pandoc. Adding highlighting may cause some misunderstandings, but it is possible to add some symbol highlighting, as shown in the following image：

<img width="329" alt="image" src="https://github.com/1943time/bluestone/assets/115093678/4cdf79bd-22e0-48b8-bcd3-cceb25b96b8b">

Unfortunately, i cannot support this feature.
