### ISSUE TITLE
新版编辑区字体显示比较虚，字体颜色偏浅灰色

### ISSUE THREAD

**Issue by zangbob** [1943time/bluestone#77]
能否增加设置字体颜色选项？或者默认为纯黑色（#000000），目前默认字体颜色好像是#3C3C3C

看得眼睛疼。。

**Comment by 1943time** [comment]
<img width="788" alt="image" src="https://github.com/1943time/bluestone/assets/115093678/b3b84f9e-ef5b-48ef-9ccf-47e3f8df0be0">
你是说上面这样？
编辑区字体颜色没有改动呀，纯黑不行的，对比度过强反而刺激眼睛。这个颜色我对比了好几个编辑器取得适中的
