### ISSUE TITLE
Failed in Windows 7

### ISSUE THREAD

**Issue by Tangent-Lin** [1943time/bluestone#79]
---------------------------
Inkdown.exe - 无法找到入口
---------------------------
无法定位程序输入点 DiscardVirtualMemory 于动态链接库 KERNEL32.dll 上。 
---------------------------
确定   
---------------------------

**Comment by 1943time** [comment]
Inkdown基于electron29开发，electron从23版本起不再支持window10以下系统，这个没办法了哈
