### ISSUE TITLE
是否能在代码块中显示行号？

### ISSUE THREAD

**Issue by haha5di** [1943time/bluestone#81]
请问客户端中编辑代码块的时候是否能显示代码行号？迫切需要这个功能，尤其是在和其他人一起讨论的时候。

感谢

**Comment by 1943time** [comment]
可以，在设置->编辑器中开启
<img width="898" alt="image" src="https://github.com/1943time/bluestone/assets/115093678/089627cb-2369-45d8-bebc-8cc1fe19961f">

**Comment by pencilheart** [comment]
可以选择不显示行号吗现在的版本？2.0.2

<img width="893" height="546" alt="Image" src="https://github.com/user-attachments/assets/95e86f20-2698-47aa-98de-2477fa6088bf" />
