### ISSUE TITLE
How to report a security issue?

### ISSUE THREAD

**Issue by sunriseXu** [1943time/bluestone#83]
Hi, there, I found a security bug in your product. How to report it, can you provide an email address, or enable github vulnerability report? Thank you! [https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing-information-about-vulnerabilities/privately-reporting-a-security-vulnerability](https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing-information-about-vulnerabilities/privately-reporting-a-security-vulnerability)

**Comment by 1943time** [comment]
My email is 1943dejavu@gmail.com
